name: Build and deploy ASP.Net Core + Angular app to Azure Web App - qa-contavida

on:
  push:
    branches:
      - qa
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # -------------------------------
      # Install Node for Angular build
      # -------------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Angular dependencies
        working-directory: ContaVida.MVC/contavida.mvc.client
        run: npm ci

      - name: Build Angular app
        working-directory: ContaVida.MVC/contavida.mvc.client
        run: npm run build --prod

      # -------------------------------
      # Setup .NET Core backend
      # -------------------------------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore backend dependencies
        run: dotnet restore ContaVida.MVC.slnx
        working-directory: ContaVida.MVC

      # -------------------------------
      # Copy Angular build to wwwroot
      # -------------------------------
      - name: Copy Angular to wwwroot
        run: |
          New-Item -ItemType Directory -Force -Path "ContaVida.MVC.Server/wwwroot"
          Copy-Item "contavida.mvc.client/dist/*" "ContaVida.MVC.Server/wwwroot" -Recurse -Force
        working-directory: ContaVida.MVC

      # -------------------------------
      # Publish backend including Angular
      # -------------------------------
      - name: Publish Website
        run: dotnet publish ContaVida.MVC.Server -c Release -o "${{env.DOTNET_ROOT}}/myapp"
        working-directory: ContaVida.MVC

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'qa-contavida'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_19972A7025904DA3AE733C41316A2169 }}
